Bottom navigation updated with Pulldown to refresh with isDeepLinking enabled with added default values for missing data without IOS Key 04

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -50,51 +50,9 @@ definitions:
         BOTTOMMENU_ICON_POSITION: $BOTTOMMENU_ICON_POSITION
         BOTTOMMENU_VISIBLE_ON: $BOTTOMMENU_VISIBLE_ON
         IS_DEEPLINK: $IS_DEEPLINK
-        flutter_build_flags: >
-          --dart-define=WEB_URL="$WEB_URL"
-          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY"
-          --dart-define=PKG_NAME="$PKG_NAME"
-          --dart-define=APP_NAME="$APP_NAME"
-          --dart-define=ORG_NAME="$ORG_NAME"
-          --dart-define=VERSION_NAME="$VERSION_NAME"
-          --dart-define=VERSION_CODE="$VERSION_CODE"
-          --dart-define=EMAIL_ID="$EMAIL_ID"
-          --dart-define=IS_SPLASH="$IS_SPLASH"
-          --dart-define=SPLASH="$SPLASH"
-          --dart-define=SPLASH_BG="$SPLASH_BG"
-          --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION"
-          --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR"
-          --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE"
-          --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR"
-          --dart-define=SPLASH_DURATION="$SPLASH_DURATION"
-          --dart-define=IS_PULLDOWN="$IS_PULLDOWN"
-          --dart-define=LOGO_URL="$LOGO_URL"
-          --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU"
-          --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS"
-          --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR"
-          --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR"
-          --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR"
-          --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR"
-          --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION"
-          --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON"
-          --dart-define=IS_DEEPLINK="$IS_DEEPLINK"
-          --dart-define=IS_CAMERA="$IS_CAMERA"
-          --dart-define=IS_LOCATION="$IS_LOCATION"
-          --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC"
-          --dart-define=IS_MIC="$IS_MIC"
-          --dart-define=IS_CONTACT="$IS_CONTACT"
-          --dart-define=IS_CALENDAR="$IS_CALENDAR"
-          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION"
-          --dart-define=IS_STORAGE="$IS_STORAGE"
-          --dart-define=firebase_config_android="$firebase_config_android"
-          --dart-define=firebase_config_ios="$firebase_config_ios"
-          --dart-define=APNS_KEY_ID="$APNS_KEY_ID"
-          --dart-define=APNS_TEAM_ID="$APNS_TEAM_ID"
-          --dart-define=APNS_AUTH_KEY_URL="$APNS_AUTH_KEY_URL"
-          --dart-define=KEY_STORE="$KEY_STORE"
-          --dart-define=CM_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
-          --dart-define=CM_KEY_ALIAS="$CM_KEY_ALIAS"
-          --dart-define=CM_KEY_PASSWORD="$CM_KEY_PASSWORD"
+        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
+        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
+        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
 
   artifacts:
     #- &ipa_file build/ios/ipa/*.ipa
@@ -150,6 +108,9 @@ definitions:
         echo "APNS_KEY_ID: $APNS_KEY_ID"
         echo "APNS_TEAM_ID: $APNS_TEAM_ID"
         echo "APNS_AUTH_KEY_URL: $APNS_AUTH_KEY_URL"
+        echo "APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY"
+        echo "APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID"
+        echo "APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER"
         
         echo "*********** Firebase Android config file ***********"
         echo "firebase_config_android: $firebase_config_android"
@@ -207,6 +168,9 @@ definitions:
             --bundle-id "$PKG_NAME" \
             --create \
             --download \
+            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
+            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
+            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
             --team-id "$APNS_TEAM_ID"; then
               echo "✅ Code signing setup complete."
             else
@@ -953,6 +917,16 @@ workflows:
       - *set_launcher_icons
       - *get_splash
       - *Update_SDK_Version
+      - name: ✅ Validate required environment variables
+        script: |
+              REQUIRED_VARS=(BUNDLE_ID TEAM_ID KEY_ID APP_STORE_CONNECT_PRIVATE_KEY APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_IDENTIFIER)
+              for VAR in "${REQUIRED_VARS[@]}"; do
+                if [ -z "${!VAR}" ]; then
+                  echo "❌ Environment variable $VAR is missing. Please set it in the app_store_credentials group."
+                  exit 1
+                fi
+              done
+              echo "✅ All required environment variables are present."
       - *autosigncode
 
 #      # Download signing files from secure URLs
