Bottom navigation updated with Pulldown to refresh with isDeepLinking enabled with added default values for missing data without IOS Key 04

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -198,6 +198,22 @@ definitions:
         echo "*********** DEEPLINK Configuration ***********"
         echo "IS_DEEPLINK: $IS_DEEPLINK"
 
+    - &autosigncode
+      name: 🔐 Automatic code signing via App Store Connect
+      script: |
+        echo "🗕 Starting automatic code signing..."
+            if app-store-connect fetch-signing-files \
+            --type IOS_APP_ADHOC \
+            --bundle-id "$PKG_NAME" \
+            --create \
+            --download \
+            --team-id "$APNS_TEAM_ID"; then
+              echo "✅ Code signing setup complete."
+            else
+              echo "❌ Failed to perform automatic code signing. Please check your credentials or App Store Connect access."
+              exit 1
+            fi
+
 
     - &get_splash
       name: Get splash screen image from splash image from Url
@@ -921,6 +937,11 @@ workflows:
     instance_type: mac_mini_m1
     environment:
       flutter: stable
+      xcode: latest
+      cocoapods: default
+      groups:
+          - firebase_credentials
+          - app_store_credentials
     scripts:
       - *change_proj_name
       - *debug_env
@@ -932,13 +953,14 @@ workflows:
       - *set_launcher_icons
       - *get_splash
       - *Update_SDK_Version
+      - *autosigncode
 
-      # Download signing files from secure URLs
-      - name: Download signing files
-        script: |
-          mkdir -p signing
-          wget -O signing/ios_certificate.p12 "$CERTIFICATE_URL"
-          wget -O signing/ios_profile.mobileprovision "$PROFILE_URL"
+#      # Download signing files from secure URLs
+#      - name: Download signing files
+#        script: |
+#          mkdir -p signing
+#          wget -O signing/ios_certificate.p12 "$CERTIFICATE_URL"
+#          wget -O signing/ios_profile.mobileprovision "$PROFILE_URL"
 
       - *build_ipa
 
@@ -948,14 +970,14 @@ workflows:
       - flutter_build2.log
       - fcm_token.txt
 
-    code_signing:
-      ios_signing:
-        certificates:
-          - certificate_path: signing/ios_certificate.p12
-            certificate_password: $CERTIFICATE_PASSWORD
-        provisioning_profiles:
-          - bundle_identifier: $PKG_NAME
-            path: signing/ios_profile.mobileprovision
+#    code_signing:
+#      ios_signing:
+#        certificates:
+#          - certificate_path: signing/ios_certificate.p12
+#            certificate_password: $CERTIFICATE_PASSWORD
+#        provisioning_profiles:
+#          - bundle_identifier: $PKG_NAME
+#            path: signing/ios_profile.mobileprovision
 
     publishing: *email_release
   ios-and-android-workflow:
