Bottom navigation updated with Pulldown to refresh with isDeepLinking enabled 12

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -666,8 +666,53 @@ definitions:
       name: Building iOS App with Feature Flags
       script: |
         echo "✅ Building iOS IPA..."
-        flutter build ipa --release $flutter_build_flags > flutter_build.log
-        echo "✅ IPA build completed."
+        flutter build ipa \
+          --release \
+          --dart-define=WEB_URL="$WEB_URL" \
+          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
+          --dart-define=PKG_NAME="$PKG_NAME" \
+          --dart-define=APP_NAME="$APP_NAME" \
+          --dart-define=ORG_NAME="$ORG_NAME" \
+          --dart-define=VERSION_NAME="$VERSION_NAME" \
+          --dart-define=VERSION_CODE="$VERSION_CODE" \
+          --dart-define=EMAIL_ID="$EMAIL_ID" \
+          --dart-define=IS_SPLASH="$IS_SPLASH" \
+          --dart-define=SPLASH="$SPLASH" \
+          --dart-define=SPLASH_BG="$SPLASH_BG" \
+          --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION" \
+          --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR" \
+          --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE" \
+          --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR" \
+          --dart-define=SPLASH_DURATION="$SPLASH_DURATION" \
+          --dart-define=IS_PULLDOWN="$IS_PULLDOWN" \
+          --dart-define=LOGO_URL="$LOGO_URL" \
+          --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU" \
+          --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS" \
+          --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR" \
+          --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR" \
+          --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR" \
+          --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR" \
+          --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION" \
+          --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON" \
+          --dart-define=IS_DEEPLINK="$IS_DEEPLINK" \
+          --dart-define=IS_CAMERA="$IS_CAMERA" \
+          --dart-define=IS_LOCATION="$IS_LOCATION" \
+          --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC" \
+          --dart-define=IS_MIC="$IS_MIC" \
+          --dart-define=IS_CONTACT="$IS_CONTACT" \
+          --dart-define=IS_CALENDAR="$IS_CALENDAR" \
+          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
+          --dart-define=IS_STORAGE="$IS_STORAGE" \
+          --dart-define=firebase_config_android="$firebase_config_android" \
+          --dart-define=firebase_config_ios="$firebase_config_ios" \
+          --dart-define=APNS_KEY_ID="$APNS_KEY_ID" \
+          --dart-define=APNS_TEAM_ID="$APNS_TEAM_ID" \
+          --dart-define=APNS_AUTH_KEY_URL="$APNS_AUTH_KEY_URL" \
+          --dart-define=KEY_STORE="$KEY_STORE" \
+          --dart-define=CM_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD" \
+          --dart-define=CM_KEY_ALIAS="$CM_KEY_ALIAS" \
+          --dart-define=CM_KEY_PASSWORD="$CM_KEY_PASSWORD" > flutter_build2.log
+          echo "✅ IPA build completed."
 
     - &build_apk
       name: Building Apk with Feature Flags
@@ -707,7 +752,52 @@ definitions:
         fi
 
         echo "✅ Building APK..."
-        flutter build apk --release $flutter_build_flags > flutter_build.log
+        flutter build apk \
+            --release \
+            --dart-define=WEB_URL="$WEB_URL" \
+            --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
+            --dart-define=PKG_NAME="$PKG_NAME" \
+            --dart-define=APP_NAME="$APP_NAME" \
+            --dart-define=ORG_NAME="$ORG_NAME" \
+            --dart-define=VERSION_NAME="$VERSION_NAME" \
+            --dart-define=VERSION_CODE="$VERSION_CODE" \
+            --dart-define=EMAIL_ID="$EMAIL_ID" \
+            --dart-define=IS_SPLASH="$IS_SPLASH" \
+            --dart-define=SPLASH="$SPLASH" \
+            --dart-define=SPLASH_BG="$SPLASH_BG" \
+            --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION" \
+            --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR" \
+            --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE" \
+            --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR" \
+            --dart-define=SPLASH_DURATION="$SPLASH_DURATION" \
+            --dart-define=IS_PULLDOWN="$IS_PULLDOWN" \
+            --dart-define=LOGO_URL="$LOGO_URL" \
+            --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU" \
+            --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS" \
+            --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR" \
+            --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR" \
+            --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR" \
+            --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR" \
+            --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION" \
+            --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON" \
+            --dart-define=IS_DEEPLINK="$IS_DEEPLINK" \
+            --dart-define=IS_CAMERA="$IS_CAMERA" \
+            --dart-define=IS_LOCATION="$IS_LOCATION" \
+            --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC" \
+            --dart-define=IS_MIC="$IS_MIC" \
+            --dart-define=IS_CONTACT="$IS_CONTACT" \
+            --dart-define=IS_CALENDAR="$IS_CALENDAR" \
+            --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
+            --dart-define=IS_STORAGE="$IS_STORAGE" \
+            --dart-define=firebase_config_android="$firebase_config_android" \
+            --dart-define=firebase_config_ios="$firebase_config_ios" \
+            --dart-define=APNS_KEY_ID="$APNS_KEY_ID" \
+            --dart-define=APNS_TEAM_ID="$APNS_TEAM_ID" \
+            --dart-define=APNS_AUTH_KEY_URL="$APNS_AUTH_KEY_URL" \
+            --dart-define=KEY_STORE="$KEY_STORE" \
+            --dart-define=CM_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD" \
+            --dart-define=CM_KEY_ALIAS="$CM_KEY_ALIAS" \
+            --dart-define=CM_KEY_PASSWORD="$CM_KEY_PASSWORD" > flutter_build.log
         if [ $? -ne 0 ]; then
         echo "❌ APK build failed"
         cat flutter_build.log
@@ -715,14 +805,14 @@ definitions:
         fi
         echo "✅ APK build completed."
 
-        echo "✅ Building AppBundle..."
-        flutter build appbundle --release $flutter_build_flags > flutter_build2.log
-        if [ $? -ne 0 ]; then
-        echo "❌ AppBundle build failed"
-        cat flutter_build2.log
-        exit 1
-        fi
-        echo "✅ AppBundle build completed."
+#        echo "✅ Building AppBundle..."
+#        flutter build appbundle --release $flutter_build_flags > flutter_build2.log
+#        if [ $? -ne 0 ]; then
+#        echo "❌ AppBundle build failed"
+#        cat flutter_build2.log
+#        exit 1
+#        fi
+#        echo "✅ AppBundle build completed."
 
 workflows:
   android-workflow:
@@ -775,6 +865,7 @@ workflows:
     artifacts:
       - *ios_app
       - flutter_build.log
+      - flutter_build2.log
       - fcm_token.txt
     #        - *android_abb
     publishing: *email_release
@@ -804,6 +895,7 @@ workflows:
         - *android_abb
         - *ios_app
         - flutter_build.log
+        - flutter_build2.log
         - fcm_token.txt
       #        - *android_abb
       publishing: *email_release
