IS Deaplink updated 03

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -51,51 +51,6 @@ definitions:
         BOTTOMMENU_VISIBLE_ON: $BOTTOMMENU_VISIBLE_ON
         IS_DEEPLINK: $IS_DEEPLINK
         IS_LOAD_IND: $IS_LOAD_IND
-        flutter_build_flags: >
-          --dart-define=WEB_URL="$WEB_URL"
-          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY"
-          --dart-define=PKG_NAME="$PKG_NAME"
-          --dart-define=APP_NAME="$APP_NAME"
-          --dart-define=ORG_NAME="$ORG_NAME"
-          --dart-define=VERSION_NAME="$VERSION_NAME"
-          --dart-define=VERSION_CODE="$VERSION_CODE"
-          --dart-define=EMAIL_ID="$EMAIL_ID"
-          --dart-define=IS_SPLASH="$IS_SPLASH"
-          --dart-define=SPLASH="$SPLASH"
-          --dart-define=SPLASH_BG="$SPLASH_BG"
-          --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION"
-          --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR"
-          --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE"
-          --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR"
-          --dart-define=SPLASH_DURATION="$SPLASH_DURATION"
-          --dart-define=IS_PULLDOWN="$IS_PULLDOWN"
-          --dart-define=LOGO_URL="$LOGO_URL"
-          --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU"
-          --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS"
-          --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR"
-          --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR"
-          --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR"
-          --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR"
-          --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION"
-          --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON"
-          --dart-define=IS_DEEPLINK="$IS_DEEPLINK"
-          --dart-define=IS_CAMERA="$IS_CAMERA"
-          --dart-define=IS_LOCATION="$IS_LOCATION"
-          --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC"
-          --dart-define=IS_MIC="$IS_MIC"
-          --dart-define=IS_CONTACT="$IS_CONTACT"
-          --dart-define=IS_CALENDAR="$IS_CALENDAR"
-          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION"
-          --dart-define=IS_STORAGE="$IS_STORAGE"
-          --dart-define=firebase_config_android="$firebase_config_android"
-          --dart-define=firebase_config_ios="$firebase_config_ios"
-          --dart-define=APNS_KEY_ID="$APNS_KEY_ID"
-          --dart-define=APNS_TEAM_ID="$APNS_TEAM_ID"
-          --dart-define=APNS_AUTH_KEY_URL="$APNS_AUTH_KEY_URL"
-          --dart-define=KEY_STORE="$KEY_STORE"
-          --dart-define=CM_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
-          --dart-define=CM_KEY_ALIAS="$CM_KEY_ALIAS"
-          --dart-define=CM_KEY_PASSWORD="$CM_KEY_PASSWORD"
 
   artifacts:
     #- &ipa_file build/ios/ipa/*.ipa
@@ -308,24 +263,6 @@ definitions:
 
         flutter pub get
         echo "✅ Completed: Logo downloaded"
-#        echo "🚀 Started: Downloading logo from $LOGO_URL"
-#
-#        mkdir -p assets/images/
-#
-#        # Try downloading with certificate check first
-#        wget -O assets/images/logo.png "$LOGO_URL"
-#        if [ $? -ne 0 ]; then
-#        echo "⚠️ Certificate issue detected, retrying with --no-check-certificate"
-#        wget --no-check-certificate -O assets/images/logo.png "$LOGO_URL"
-#        fi
-#
-#        if [ ! -f assets/images/logo.png ]; then
-#        echo "❌ Error: Failed to download logo from $LOGO_URL"
-#        exit 1
-#        fi
-#
-#        flutter pub get
-#        echo "✅ Completed: Logo downloaded"
 
     - &set_launcher_icons
       name: Generate Launcher Icons
@@ -368,8 +305,6 @@ definitions:
            flutter pub run flutter_launcher_icons
 
            echo "✅ Launcher icons generated successfully"
-#        flutter pub run flutter_launcher_icons:main
-#        flutter pub get
 
 
     - &change_app_name
@@ -411,44 +346,9 @@ definitions:
       
           echo "✅ App name changed and version set successfully"
 
-#        flutter pub run rename setAppName --value "$APP_NAME"
-#        flutter pub get
 
-    - &update_android_package
-      name: Update Android Package Name
-      script: |
-        echo "Updating Android package name..."
 
-        # Convert ORG_NAME and APP_NAME to lowercase and remove spaces/underscores
-        CLEANED_ORG_NAME=$(echo "$ORG_NAME" | tr '[:upper:]' '[:lower:]' | tr -d ' _')
-        CLEANED_APP_NAME=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | tr -d ' _')
-
-        # Construct valid package name
-        # PACKAGE_NAME="com.${CLEANED_ORG_NAME}.${CLEANED_APP_NAME}"
-        # Prefer PKG_NAME if available
-        if [ -n "$PKG_NAME" ]; then
-        PACKAGE_NAME="$PKG_NAME"
-        else
-          PACKAGE_NAME="${CLEANED_ORG_NAME}.${CLEANED_APP_NAME}"
-        fi
-
-        # Validate package name format
-        if [[ ! "$PACKAGE_NAME" =~ ^[a-zA-Z_][a-zA-Z0-9]*(\.[a-zA-Z_][a-zA-Z0-9]*)+$ ]]; then
-          echo "❌ ERROR: Invalid package name: $PACKAGE_NAME"
-          exit 1
-        fi
-
-        echo "✔ Package name: $PACKAGE_NAME"
-
-        flutter pub run rename setBundleId  --value "$PACKAGE_NAME"
-
-        # Update AndroidManifest.xml
-        sed -i '' "s/package=\"[^\"]*\"/package=\"$PACKAGE_NAME\"/g" android/app/src/main/AndroidManifest.xml
-
-        # Update applicationId in build.gradle
-        sed -i '' "s/applicationId \"[^\"]*\"/applicationId \"$PACKAGE_NAME\"/g" android/app/build.gradle
-
-        echo "✔ Package name updated to: $PACKAGE_NAME"
+   
 
     - &Inject_Firebase_iOS_Push
       name: Firebase Push Notification Setup for iOS
@@ -525,18 +425,7 @@ definitions:
         echo "🚫 Firebase config skipped (PUSH_NOTIFY is not true)"
         fi
 
-#         if [ "$PUSH_NOTIFY" = "true" ]; then
-#          echo "📥 Downloading google-services.json..."
-#
-#          # Ensure target directories exist
-#          mkdir -p android/app
-#          mkdir -p assets
-#
-#          wget -O android/app/google-services.json "$firebase_config_android"
-#          wget -O assets/google-services.json "$firebase_config_android"
-#        else
-#          echo "🚫 Firebase config skipped (PUSH_NOTIFY is not true)"
-#        fi
+
 
     - &Inject_Firebase
       name: Inject Firebase and buildscript block
@@ -826,14 +715,73 @@ definitions:
         fi
         echo "✅ APK build completed."
 
-#        echo "✅ Building AppBundle..."
-#        flutter build appbundle --release $flutter_build_flags > flutter_build2.log
-#        if [ $? -ne 0 ]; then
-#        echo "❌ AppBundle build failed"
-#        cat flutter_build2.log
-#        exit 1
-#        fi
-#        echo "✅ AppBundle build completed."
+        echo "✅ Building AppBundle..."
+        flutter build appbundle --release \
+           --dart-define=WEB_URL="$WEB_URL" \
+            --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
+            --dart-define=PKG_NAME="$PKG_NAME" \
+            --dart-define=APP_NAME="$APP_NAME" \
+            --dart-define=ORG_NAME="$ORG_NAME" \
+            --dart-define=VERSION_NAME="$VERSION_NAME" \
+            --dart-define=VERSION_CODE="$VERSION_CODE" \
+            --dart-define=EMAIL_ID="$EMAIL_ID" \
+            --dart-define=IS_SPLASH="$IS_SPLASH" \
+            --dart-define=SPLASH="$SPLASH" \
+            --dart-define=SPLASH_BG="$SPLASH_BG" \
+            --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION" \
+            --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR" \
+            --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE" \
+            --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR" \
+            --dart-define=SPLASH_DURATION="$SPLASH_DURATION" \
+            --dart-define=IS_PULLDOWN="$IS_PULLDOWN" \
+            --dart-define=LOGO_URL="$LOGO_URL" \
+            --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU" \
+            --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS" \
+            --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR" \
+            --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR" \
+            --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR" \
+            --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR" \
+            --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION" \
+            --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON" \
+            --dart-define=IS_DEEPLINK="$IS_DEEPLINK" \
+            --dart-define=IS_LOAD_IND="$IS_LOAD_IND" \
+            --dart-define=IS_CAMERA="$IS_CAMERA" \
+            --dart-define=IS_LOCATION="$IS_LOCATION" \
+            --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC" \
+            --dart-define=IS_MIC="$IS_MIC" \
+            --dart-define=IS_CONTACT="$IS_CONTACT" \
+            --dart-define=IS_CALENDAR="$IS_CALENDAR" \
+            --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
+            --dart-define=IS_STORAGE="$IS_STORAGE" \
+            --dart-define=firebase_config_android="$firebase_config_android" \
+            --dart-define=firebase_config_ios="$firebase_config_ios" \
+            --dart-define=APNS_KEY_ID="$APNS_KEY_ID" \
+            --dart-define=APNS_TEAM_ID="$APNS_TEAM_ID" \
+            --dart-define=APNS_AUTH_KEY_URL="$APNS_AUTH_KEY_URL" \
+            --dart-define=KEY_STORE="$KEY_STORE" \
+            --dart-define=CM_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD" \
+            --dart-define=CM_KEY_ALIAS="$CM_KEY_ALIAS" \
+            --dart-define=CM_KEY_PASSWORD="$CM_KEY_PASSWORD" > flutter_build_aab.log
+        if [ $? -ne 0 ]; then
+        echo "❌ AppBundle build failed"
+        cat flutter_build2.log
+        exit 1
+        fi
+        echo "✅ AppBundle build completed."
+    - &key_store
+      name: Setup Android keystore and insert Gradle signing block
+      script: |
+        echo "✅ Downloading keystore..."
+        curl -o android/app/keystore.jks "$KEY_STORE"
+        
+        echo "✅ Writing key.properties..."
+        cat > android/key.properties <<EOF
+        storeFile=keystore.jks
+        storePassword=$CM_KEYSTORE_PASSWORD
+        keyAlias=$CM_KEY_ALIAS
+        keyPassword=$CM_KEY_PASSWORD
+        EOF
+
 
 workflows:
   android-workflow:
@@ -856,13 +804,14 @@ workflows:
       - *get_logo
       - *set_launcher_icons
       - *get_splash
+      - *key_store
       - *build_apk
 #      - *build_ipa
     artifacts:
       - *android_apk
       - *android_abb
-      - *ios_app
       - flutter_build.log
+      - flutter_build_aab.log
       - fcm_token.txt
     #        - *android_abb
     publishing: *email_release
